[workspace]

members = [
    "vrf",
    "session-keys",
    "pallets/author-inherent",
    "pallets/author-mapping",
    "pallets/author-slot-filter",
    "pallets/parachain-staking",
    "pallets/randomness",
    "nimbus-consensus",
    "nimbus-primitives",
]
